### ISSUE TITLE
Exported Jira heading level always starts at 1 

### ISSUE THREAD

**Issue by kickingvegas** [stig/ox-jira.el#54]
When exporting org-mode subtree, the exported Jira heading level is set to `1`. Would prefer that this matches the actual org heading level.

**Comment by kickingvegas** [comment]
Also thanks so much for this exporter - so tremendously useful.

**Comment by mikej96** [comment]
@kickingvegas - 

I also use ox-jira very frequently it is a huge time saver for me. I agree it would be nice to have the export match the org level or have a mechanism to have a 'default' top level. I find that in jira the h1 and h2 headings are obnoxiously large, and for me I like to make the top level be h3. 

To work around this I have modified my ox-jira.el's `ox-jira-headline` fucnction with the following so that my top level always starts with h3. 

` (format "h%d. %s%s%s\n" (+ 2 level) todo-text title tags-text) `


![image](https://user-images.githubusercontent.com/19496159/93655911-26656a00-f9ec-11ea-88fd-1b217a21e85d.png)

I am sure there is a better way to do this so I am not modifying the package file directly but I am not sure how to do it. 

Thank you @stig for the excellent package!

**Comment by stig** [comment]
Hi, I've attempted to address both your concerns in https://github.com/stig/ox-jira.el/pull/55 -- can you please let me know if it works for you, and reopen the ticket if it does not? (You'll probably have to wait a day for MELPA to get the new version.)

**Comment by stig** [comment]
PS: thank you for the kind words!

**Comment by mikej96** [comment]
@stig you rock! Works perfectly! Thank you!!
